# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelled', models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('S', 'Shopping'), ('F', 'FInance'), ('O', 'Others')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_set', models.CharField(choices=[('N', 'New'), ('P', 'Progress'), ('C', 'Completed')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_desc', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_list.Label')),
            ],
        ),
    ]
